source('basic_classifiers.R')
source('common.R')
source('cross_validation.R')
source('forward_stepwise.R')
source('pca.R')

print(paste(date(),'loading training data...'),quote=FALSE)
trainingData <- as.matrix(read.csv('../data/train.csv',header=FALSE))
yTrain <- as.matrix(read.csv('../data/ytrain.csv',header=FALSE))
print(paste(date(),'finished; stored word count vectors in trainingData, classes in yTrain'),quote=FALSE)
